name: CI

on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        run: sudo apt-get install -y golang-go
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: executing remote ssh commands
        uses: ./
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if [ '${{ steps.extract_branch.outputs.branch }}' == 'development' ]; then
              cd /var/www/project/bukabengkel/bukabengkel-api-go
              git checkout .
              git pull origin development
              go mod tidy
              go build -o main .
              service bukabengkel restart
            else
              echo 'wrong branch'
            fi
