name: CI

on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if [ '${{ steps.extract_branch.outputs.branch }}' == 'development' ]; then
              export PATH=$PATH:/usr/local/go/bin
              cd /var/www/project/bukabengkel/bukabengkel-api-go
              git checkout .
              git pull origin development
              go mod tidy
              go build -o main .
              supervisorctl restart bukabengkel-api-go
            else
              echo 'wrong branch'
            fi
          
