name: CI

on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            DEPLOY_PATH=""
            SERVICE_NAME=""
            if [ "${{ env.BRANCH_NAME }}" == "development" ]; then
              DEPLOY_PATH="/var/www/project/bukabengkel/bukabengkel-api-go"
              SERVICE_NAME="bukabengkel-api-go"
            elif [ "${{ env.BRANCH_NAME }}" == "master" ]; then
              DEPLOY_PATH="/var/www/project/bukabengkel/bukabengkel-api-go-production"
              SERVICE_NAME="bukabengkel-api-go-production"
            else
              echo 'wrong branch'
              exit 1
            fi
            cd $DEPLOY_PATH
            git checkout .
            GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa" git pull
            go mod tidy
            go build -o main .
            supervisorctl restart $SERVICE_NAME
            
